services:
  - type: web
    name: carrier-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_STORE
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_API_VERSION
        value: 2024-01
      - key: NEXT_PUBLIC_APP_URL
        sync: false
